name: License Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: license check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Check files
        run: go run scripts/license_check.go
